"use client";
import { useState, useEffect } from "react";
import Link from "next/link";
import { apiGet } from "@/lib/api";
import { usePersistedState } from "@/lib/usePersistedState";

// Mirrors PracticeScreen.kt — Tabs MCQs/Coding/PYQs, backend: quizzes/codingChallenges/pyqs
type Tab="mcq"|"coding"|"pyq";
export default function Practice(){
  const [tab,setTab]=usePersistedState<Tab>("vastavik_practice_tab","mcq");
  const [quizzes,setQuizzes]=useState<any[]>([]);
  useEffect(()=>{ apiGet<{data:any[]}>("/api/v1/lessons?limit=5").catch(()=>{}); },[]);
  return (
    <div className="space-y-4 min-h-[80vh] bg-zinc-950 text-white -mx-4 px-4 -mt-6 pt-6 pb-8 rounded-b-3xl">
      <h1 className="text-xl font-bold">Practice</h1>
      <div className="flex gap-2 bg-zinc-800 p-1 rounded-2xl w-fit">
        {(["mcq","coding","pyq"] as Tab[]).map(t=> <button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 rounded-xl text-sm font-semibold ${tab===t?"bg-white text-zinc-900 shadow":"text-zinc-400"}`}>{t==="mcq"?"MCQs":t==="coding"?"Coding":"PYQs"}</button>)}
      </div>

      {tab==="mcq" && (
        <div className="space-y-3">
          {[["OOP Concepts","10 questions"],["Arrays & Lists","15 questions"],["Sorting","12 questions"],["File Handling","8 questions"]].map(([title,sub])=> (
            <button key={title} onClick={()=>window.location.href=`/quiz/setup/${encodeURIComponent(title)}`} className="w-full text-left bg-zinc-900 border border-zinc-800 rounded-2xl p-4 flex justify-between items-center hover:bg-zinc-800 transition">
              <div className="flex gap-3 items-center"><span className="w-12 h-12 rounded-xl bg-brand/20 grid place-items-center text-lg">🧠</span><div><p className="font-semibold">{title}</p><p className="text-xs text-zinc-400">{sub}</p></div></div><span className="text-zinc-500">›</span>
            </button>
          ))}
          <p className="text-xs text-zinc-600">Quizzes generated by Mistral AI — same as Kotlin QuizManager.generateQuiz</p>
        </div>
      )}
      {tab==="coding" && (
        <div className="space-y-3">
          {[
            ["Reverse a String","Easy","Strings"],
            ["Two Sum","Medium","Arrays"],
            ["Merge Intervals","Hard","Intervals"],
          ].map(([t,diff,topic])=> (
            <Link key={t} href="/code-editor" className="block bg-zinc-900 border border-zinc-800 rounded-2xl p-4 hover:bg-zinc-800 transition">
              <div className="flex justify-between"><p className="font-semibold">{t}</p><span className={`text-xs px-2 py-1 rounded-full ${diff==="Easy"?"bg-green-900/50 text-green-400":diff==="Medium"?"bg-amber-900/50 text-amber-400":"bg-red-900/50 text-red-400"}`}>{diff}</span></div>
              <p className="text-xs text-zinc-400">{topic}</p>
            </Link>
          ))}
        </div>
      )}
      {tab==="pyq" && (
        <div className="space-y-3">
          {[["ICSE 2023","45 questions"],["CBSE 2022","50 questions"],["ICSE 2022","40 questions"]].map(([t,s])=> (
            <Link key={t} href="/pyq" className="block bg-zinc-900 border border-zinc-800 rounded-2xl p-4 flex justify-between hover:bg-zinc-800 transition"><div><p className="font-semibold">{t}</p><p className="text-xs text-zinc-400">{s}</p></div><span className="text-zinc-500">›</span></Link>
          ))}
        </div>
      )}
    </div>
  );
}
